Repository codezonediitj/codezonediitj.github.io, pull requests merged in 2019-06, with the labels that each got.

#16 Added templates in .github/
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Workflow

#23 Added Competitive Programming Learning Path as a blog post
  _posts/2017-11-14-Dennis-Ritchie-Father-of-C.md
  _posts/2017-11-14-Google-Lens-It's-Amazing!!!.md
  _posts/2017-11-14-Link-Analysis-Why-Is-It-Important.md
  _posts/2017-11-16-Humans-innovate-machines-calculate-Can-machines-think.md
  _posts/2017-12-09-Brainfuck.md
  _posts/2017-12-23-The-Man-Who-Knew-Infinity.md
  _posts/2018-02-11-Tony-Stark.md
  _posts/2018-02-13-The-Weirdest-Coincidence.md
  _posts/2018-02-24-AUGMENTED-REALITY.md
  _posts/2018-03-14-The-End-of-an-Era.md
  _posts/2018-10-10-Ada-Lovelace-First-Computer-Programmer.md
  _posts/2018-10-17-Paul-Allen.md
  _posts/2019-05-26-Inception-Bar-A-new-type-of-phishing-attack.md
  _posts/2019-05-30-CPU-GPU-and-TPU-in-Deep-Learning.md
  _posts/2019-06-15-cplp.md
  index.html
Labels: blog, enhancement

#29 added blog entry-World wifi day
  _posts/2019-06-24-World-WiFi-Day.md
  images/wifi.png
Labels: blog
